spring:
  # config:
  #   activate:
  #     on-profile: dev

  datasource:
    url: jdbc:h2:mem:file-handler
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart.max-file-size: 500KB
    multipart.max-request-size: 500KB
---
logging:
  level:
    root: INFO

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart.max-file-size: 500KB
    multipart.max-request-size: 500KB
